### PR TITLE
Fixes/Improves Meme Vote Handling and Adds Error Snackbar on Failed Vote

### LINKED ISSUE #60: Restructure Meme Vote Handling
The code should not rely on the server returning the new meme vote value but rather it should infer it from whether the call succeeded or not.

### PR DESCRIPTION
**Pull request by Step7750**
* Properly handles the server returning just a message as a reply
* Refactors voting with async/await
* Adds snackbar error if voting fails

Closes #60

### CODE REVIEW

File: src/app/meme-card/meme-card.component.ts [hunk 1]
```diff
@@ -58,43 +61,25 @@ export class MemeCardComponent implements OnInit {
...
-        }else{
-          this.totalVote = this.totalVote-1;
-        }
-        this.myVote = memeVote.diff;
-      }).catch((err) => {
-        console.log(err.toString());
-      });
+  async onClickDownVote() {
+    try {
+      const promise = (this.myVote === -1) ? this.memeService.deleteMemeVote(this.memeId): this.memeService.downvoteMeme(this.memeId);
```
Comment (xiningchen) [inline src/app/meme-card/meme-card.component.ts]: oh that's much nicer way to write this, lol
